name: Task CI

on:
  workflow_dispatch:
  #push:
    #branches:
    #- 'main'

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build and push bird and birdImage APIs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push bird API
      uses: docker/build-push-action@v6
      with:
        context: ./apis/bird
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/bird-api:${{ env.IMAGE_TAG }}
    - name: Build and push birdImage API
      uses: docker/build-push-action@v6
      with:
        context: ./apis/birdImage
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/birdimage-api:${{ env.IMAGE_TAG }}

  update_tags:
    name: Update the image tags of both APIs in another GitHub repository
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out kubernetes-helm repository
      uses: actions/checkout@v3
      with:
       repository: 'Agnes4Him/kubernetes-helm'
       ref: 'main'
       token: ${{ secrets.TOKEN }}
    - name: Set up Git config
      run: |
          git config user.name "Agnes4Him"
          git config user.email "ojuhagnes@gmail.com"
          git config --unset-all http.https://github.com/.extraheader
    - name: Update helm values files
      run: |
          sed -i "s/tag: .*/tag: $IMAGE_TAG/g" apis/values/bird-api-values.yaml
          sed -i "s/tag: .*/tag: $IMAGE_TAG/g" apis/values/birdimage-api-values.yaml
    - name: Commit changes
      run: |
          git add apis/values/bird-api-values.yaml apis/values/birdimage-api-values.yaml
          git commit -m "updated the image tags in bird-api and birdimage-api values files"
    - name: Push changes to GitHub
      run: |
          git push https://Agnes4Him:${{ secrets.TOKEN }}@github.com/Agnes4Him/kubernetes-helm

  deploy:
    name: Run Terraform and deploy APIs
    runs-on: ubuntu-latest
    needs: [build, update_tags]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
          terraform_wrapper: false
    - name: Terraform plan
      id: tf-plan
      working-directory: 'infrastructures'
      run: |
          terraform init && terraform plan -var-file=vars/task.tfvars
    - name: Terraform Apply
      id: tf-apply
      working-directory: 'infrastructures'
      if: ${{ steps.tf-plan.outcome }} == 'success'
      run: |
          terraform apply -auto-approve -var-file=vars/task.tfvars